### ISSUE TITLE
Guest Additions fail to compile on CentOS9/Alma9/etc, struct drm_driver̉ has no member named ‘lastclose'

### ISSUE THREAD

**Issue by psmears** [VirtualBox/virtualbox#12]
As reported in [this thread](https://forums.virtualbox.org/viewtopic.php?t=112534) (although several different issues are reported in that thread), VirtualBox Guest Additions fail to compile on CentOS9/Alma9 (and presumably also RHEL9).

This is still seen with VirtualBox 7.1.8.

The compile error is as follows:
```
/tmp/vbox.0/vbox_drv.c:372:10: error: ‘struct drm_driver̉ has no member named ‘lastclosẻ; did you mean ‘postclosẻ?
  372 |         .master_drop = vbox_master_drop,
      |          ^~~~~~~~~
      |          postclose
/tmp/vbox.0/vbox_drv.c:372:22: error: initialization of ‘const struct drm_ioctl_desc *̉ from incompatible pointer type ‘void (*)(struct drm_device *)̉ [-Werror=incompatible-pointer-types]
  372 |         .master_drop = vbox_master_drop,
      |                      ^~~~~~~~~~~~~~~~~~~
/tmp/vbox.0/vbox_drv.c:372:22: note: (near initialization for ‘driver.ioctls̉)
cc1: some warnings being treated as errors
```

The error (at least, the `lastclose` part) seems to be because RedHat have backported some DRM changes from later kernels to this version: the affected lines of `vbox_drv.c` look like this:

```
#if RTLNX_VER_MAX(6,12,0)
        .lastclose = vbox_driver_lastclose,
#endif
``` 

... and indeed, in kernel.org kernels `lastclose` wasn't removed until kernel version 6.12 - but CentOS9 etc have 5.14.0 but with the later DRM changes backported, so the `#if` takes a path that doesn't match the kernel source.

This seems to be similar to [VirtualBox issue 19391](https://www.virtualbox.org/ticket/19391?cversion=3&cnum_hist=12), where backported DRM changes caused the guest additions to fail to compile on RedHat-flavour kernels; perhaps a similar workaround can be used in this case.

**Comment by kirchwitz** [comment]
Same problem here with the original RHEL 9.6 release. (No wonder, kernel version is still the same.)

In recent Linux Guest Additions 7.1.10, the code in vbox_drv.c looks like this:

#if RTLNX_VER_MAX(6,12,0) && !RTLNX_RHEL_RANGE(9,7, 9,99)
	.lastclose = vbox_driver_lastclose,
#endif

So there already is an additional check for the RHEL version, but it starts with 9.7 (not yet available). Maybe it should start with 9.6 (or even earlier). Or the negation "!" should be removed to only cover future releases (although I don't think that Red Hat will provide a workaround, so this line of code probably will not be valid for any RHEL 9.x version from now on).

**Comment by Achim-Haag** [comment]
Without deeper knowledge of Linux kernel, but same in RHEL 9.6, here an excerpt.

RHEL 8.10 
/usr/src/kernels/4.18.0-553.53.1.el8_10.x86_64/include/drm/drm_drv.h
```
  struct drm_driver {
     void (*postclose) (struct drm_device *, struct drm_file *);
     void (*lastclose) (struct drm_device *);
     void (*unload) (struct drm_device *);
```

RHEL 9.6 : 
/usr/src/kernels/5.14.0-570.22.1.el9_6.x86_64/include/drm/drm_drv.h
```
  struct drm_driver {
     void (*postclose) (struct drm_device *, struct drm_file *);
     void (*unload) (struct drm_device *);
```

...although [kernel.org *struct drm_driver*](https://www.kernel.org/doc/html/v5.14/gpu/drm-internals.html?highlight=lastclose#c.drm_driver) shows _void (*lastclose) (struct drm_device *);_ in drm_driver struct, but maybe related to [this fedora documentation](https://fedoraproject.org/wiki/Changes/ReplaceFbdevDrivers), Fedora (and subsequently removed parts of drm_drv.h - but I'm just a dumbass without kernel knowledge):

*Detailed Description*

*The fbdev subsystem has been deprecated for over a decade and no new platform should use it but instead write DRM drivers for their video output.*

*Yet, the Fedora kernel still enables support for some of the fbdev drivers. Mainly for fbdev drivers that make use of the video frame buffer that was initialized by the firmware. These are generic drivers that could be used in different platforms since only grab an existing frame buffer without trying to do any hardware initialization and setup.*

*Examples of these drivers are simplefb (used in aarch64 machines with Device Trees) and efifb (used in EFI machines) and vesafb (used in machines with a VESA VGA graphics). But __since the Linux v5.14, a new simpledrm driver was introduced that is able to do the same that these fbdev drivers__. And just like any other DRM driver, it can rely on the DRM subsystem fbdev emulation layer to provide a fbdev interface.*

*__For this reason, there is no need for the fbdev drivers anymore and instead the simpledrm driver could just be used.__*
     
So that may be the reason why Fedora and its dependents removed parts of struct drm_driver starting with Kernel 5.14 and so RHEL 9.x too...but as I stated: my knowledge to these things is limited...

Edit: installed Fedora 32, 34, 35, 42 (Kernel 5+6), delivered "lastclose" in drm_drv.h

**Comment by atvseth** [comment]
My experience in getting it working (this is Rocky 9.6):

Make sure your host machine has the latest version of VirtualBox.

Install a bunch of various things:
```
dnf config-manager --set-enabled crb;
dnf -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm;
dnf clean all; dnf -y update kernel* wget tar bzip2 dkms;
yum -y groupinstall 'Development Tools' --setopt=group_package_types=mandatory,default,optional;
dnf clean all; dnf -y update;
```
^ reboot after that.

Then, do NOT install guest additions from commandline.  Use VirtualBox itself: https://developer.hashicorp[.]com/vagrant/docs/providers/virtualbox/boxes

Basically, install from the GUI of VirtualBox, instead of inside the guest VM.  Screenshot here of what to click, and what the console looked like.:

<img width="289" height="252" alt="Image" src="https://github.com/user-attachments/assets/1f56a7e1-2f4c-4a77-b37f-cdf5a45f5ace" />

<img width="1039" height="735" alt="Image" src="https://github.com/user-attachments/assets/d741578b-e256-4b65-97e5-1846005450a0" />

For what it's worth, I had selinux in permissive, and the rest of the Rocky 9 image is stock.  I didn't do anything to rc.local.

`systemctl status vboxadd.service` in the guest VM shows the service running on the latest Guest Additions (7.1.10)

```
[root@vbox ~]# systemctl status vboxadd.service
● vboxadd.service
     Loaded: loaded (/opt/VBoxGuestAdditions-7.1.10/init/vboxadd; enabled; preset: disabled)
     Active: active (exited) since Thu 2025-07-10 05:46:56 PDT; 53s ago
    Process: 19428 ExecStart=/opt/VBoxGuestAdditions-7.1.10/init/vboxadd start (code=exited, status=0/SUCCESS)
   Main PID: 19428 (code=exited, status=0/SUCCESS)
        CPU: 452ms

Jul 10 05:46:56 vbox systemd[1]: Starting vboxadd.service...
Jul 10 05:46:56 vbox vboxadd[19428]: VirtualBox Guest Additions: Starting.
Jul 10 05:46:56 vbox systemd[1]: Finished vboxadd.service.

[root@vbox ~]# lsmod | grep vboxguest
vboxguest             536576  2

[root@vbox ~]# /usr/sbin/VBoxService --version
7.1.10r169112
```

And setting up Shared Folders (something Guest Additions does), works

<img width="1044" height="122" alt="Image" src="https://github.com/user-attachments/assets/d4d971b9-afc3-4b84-9624-52305bbad603" />

```
[root@vbox ~]# ll /mnt/HostDownloads/Rocky-9.6-x86_64-minimal.iso
-rwxrwx---. 1 root vboxsf 2252013568 May 29 17:12 /mnt/HostDownloads/Rocky-9.6-x86_64-minimal.iso
```

**Comment by Achim-Haag** [comment]
Thanks for your hint, but ass I rolled back my VM to RHEL 8.10 (supported until 2029, private development machine), I'm actually not able to test it.

I have to state that even with this error the VM behaved normally and cannot say what consequences - if any - the mentioned error has.

When I have a little time, I will retry the upgrade and test your method. I use my environment for personal interests and self-education, so it's not business critical in any way.

Another option may be to wait til RHEL offers an inline upgrade from RHEL 8.10 to >9.6 as the usage of drm_driver.lastclose seems skipped by the precompiler.

**Comment by CaptainFlint** [comment]
For what it's worth, I managed to build the guest drivers for the latest Rocky 9.6 kernels by commenting out that removed `lastclose` member of the structure:
/opt/VBoxGuestAdditions-7.1.10/src/vboxguest-7.1.10/vboxvideo/vbox_drv.c
```c
static struct drm_driver driver = {
    /* ...skipped... */
#if RTLNX_VER_MAX(4,19,0) && !RTLNX_RHEL_MAJ_PREREQ(8,3)
    /* Legacy hooks, but still supported. */
    .load = vbox_driver_load,
    .unload = vbox_driver_unload,
#endif
#if RTLNX_VER_MAX(6,12,0) && !RTLNX_RHEL_RANGE(9,7, 9,99)
/*  .lastclose = vbox_driver_lastclose,    <<< NOW COMMENTED */
#endif
    .master_set = vbox_master_set,
    .master_drop = vbox_master_drop,
    /* ... */
```
However, I can't guarantee it won't cause any side effects. So far it's been working fine on my machine which I'm using constantly, but I never checked for possible memory or handle leaks. The current kernel is 5.14.0-570.23.1.el9_6.x86_64.

**Comment by alexgit2k** [comment]
Same problem with Rocky Linux 9.6 and VirtualBox 7.2.0. Got it also running by removing the line `.lastclose = vbox_driver_lastclose,`like in the comment before with the following commands after the GuestAdditions are mounted:

```bash
# Extract source
sudo su
cd /opt
/mnt/VBoxLinuxAdditions.run --noexec --keep
mkdir /opt/vbox
tar -xjf /opt/install/VBoxGuestAdditions-amd64.tar.bz2 -C /opt/vbox

# Apply workaround
sed -i '/\.lastclose = vbox_driver_lastclose/d' /opt/vbox/src/vboxguest-*/vboxvideo/vbox_drv.c

# Repack and Install
tar -cjf /opt/install/VBoxGuestAdditions-amd64.tar.bz2 -C /opt/vbox .
sed -i '$ s/^/#/' /usr/sbin/vbox-uninstall-guest-additions
cd /opt/install/
./install.sh

# Cleanup
rm -rf /opt/vbox /opt/install /opt/VBoxGuestAdditions-*
```

**Comment by alexgit2k** [comment]
Same issue with VirtualBox 7.2.2.

**Comment by galitsyn-oracle** [comment]
This issue should now be fixed in the latest "Development snapshots" Additions build (r170642 and newer) from https://www.virtualbox.org/wiki/Testbuilds. Could you please give it a try?

**Comment by mabrarov** [comment]
Hi @galitsyn-oracle,

> This issue should now be fixed in the latest "Development snapshots" Additions build (r170642 and newer) from https://www.virtualbox.org/wiki/Testbuilds. Could you please give it a try?

I tried Guest Additions from https://www.virtualbox.org/download/testcase/VBoxGuestAdditions_7.2.3-170642.iso and got following (issue is not solved):

```text
$ cat /etc/*release
NAME="Rocky Linux"
VERSION="9.6 (Blue Onyx)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="9.6"
PLATFORM_ID="platform:el9"
PRETTY_NAME="Rocky Linux 9.6 (Blue Onyx)"
ANSI_COLOR="0;32"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:rocky:rocky:9::baseos"
HOME_URL="https://rockylinux.org/"
VENDOR_NAME="RESF"
VENDOR_URL="https://resf.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
SUPPORT_END="2032-05-31"
ROCKY_SUPPORT_PRODUCT="Rocky-Linux-9"
ROCKY_SUPPORT_PRODUCT_VERSION="9.6"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.6"
Rocky Linux release 9.6 (Blue Onyx)
Rocky Linux release 9.6 (Blue Onyx)
Rocky Linux release 9.6 (Blue Onyx)

$ uname -r
5.14.0-570.39.1.el9_6.x86_64

$ sudo mount -r /dev/cdrom /mnt/cdrom

$ ll /mnt/cdrom/
total 41949
-r--r--r-- 1 root root    1049 Aug 11 21:04 AUTORUN.INF
-r-xr-xr-x 1 root root    7114 Sep 25 09:37 autorun.sh
dr-xr-xr-x 2 root root    1468 Sep 25 10:13 cert
dr-xr-xr-x 2 root root    1252 Sep 25 10:13 NT3x
dr-xr-xr-x 2 root root    2828 Sep 25 10:13 OS2
-r-xr-xr-x 1 root root    5097 Sep 25 09:37 runasroot.sh
-r--r--r-- 1 root root     718 Sep 25 10:13 TRANS.TBL
-r--r--r-- 1 root root 2204046 Sep 25 09:54 VBoxDarwinAdditions.pkg
-r-xr-xr-x 1 root root    4225 Sep 25 09:54 VBoxDarwinAdditionsUninstall.tool
-r-xr-xr-x 1 root root 2908188 Sep 25 09:42 VBoxLinuxAdditions-arm64.run
-r-xr-xr-x 1 root root 6656007 Sep 25 09:38 VBoxLinuxAdditions.run
-r--r--r-- 1 root root 9559552 Sep 25 09:39 VBoxSolarisAdditions.pkg
-r-xr-xr-x 1 root root 8720296 Sep 25 10:12 VBoxWindowsAdditions-amd64.exe
-r-xr-xr-x 1 root root 5052224 Sep 25 10:01 VBoxWindowsAdditions-arm64.exe
-r-xr-xr-x 1 root root 1074392 Sep 25 09:39 VBoxWindowsAdditions.exe
-r-xr-xr-x 1 root root 6752880 Sep 25 10:02 VBoxWindowsAdditions-x86.exe
-r--r--r-- 1 root root     261 Mar 10  2023 windows11-bypass.reg

$ sudo /mnt/cdrom/VBoxLinuxAdditions.run
Verifying archive integrity...  100%   MD5 checksums are OK. All good.
Uncompressing VirtualBox 7.2.3 Guest Additions for Linux  100%
VirtualBox Guest Additions installer
VirtualBox Guest Additions: Starting.
VirtualBox Guest Additions: Setting up modules
VirtualBox Guest Additions: Building the VirtualBox Guest Additions kernel
modules.  This may take a while.
VirtualBox Guest Additions: To build modules for other installed kernels, run
VirtualBox Guest Additions:   /sbin/rcvboxadd quicksetup <version>
VirtualBox Guest Additions: or
VirtualBox Guest Additions:   /sbin/rcvboxadd quicksetup all
VirtualBox Guest Additions: Building the modules for kernel
5.14.0-570.39.1.el9_6.x86_64.

VirtualBox Guest Additions: Look at /var/log/vboxadd-setup.log to find out what
went wrong
VirtualBox Guest Additions: reloading kernel modules and services
VirtualBox Guest Additions: kernel modules and services 7.2.3 r170642 reloaded
VirtualBox Guest Additions: NOTE: you may still consider to re-login if some
user session specific services (Shared Clipboard, Drag and Drop, Seamless or
Guest Screen Resize) were not restarted automatically

$ cat /var/log/vboxadd-setup.log
...
  gcc -Wp,-MMD,/tmp/vbox.0/.vbox_ttm.o.d -nostdinc -I./arch/x86/include -I./arch/x86/include/generated  -I./include -I./arch/x86/include/uapi -I./arch/x86/include/generated/uapi -I./include/uapi -I./include/generated/uapi -include ./include/linux/compiler-version.h -include ./include/linux/kconfig.h -include ./include/linux/compiler_types.h -D__KERNEL__ -fmacro-prefix-map=./= -Wall -Wundef -Werror=strict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -fshort-wchar -fno-PIE -Werror=implicit-function-declaration -Werror=implicit-int -Werror=return-type -Wno-format-security -std=gnu11 -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -mno-avx -fcf-protection=none -m64 -falign-jumps=1 -falign-loops=1 -mno-80387 -mno-fp-ret-in-387 -mpreferred-stack-boundary=3 -mskip-rax-setup -mtune=generic -mno-red-zone -mcmodel=kernel -Wno-sign-compare -fno-asynchronous-unwind-tables -mindirect-branch=thunk-extern -mindirect-branch-register -mindirect-branch-cs-prefix -mfunction-return=thunk-extern -fno-jump-tables -mharden-sls=all -fpatchable-function-entry=16,16 -fno-delete-null-pointer-checks -Wno-frame-address -Wno-format-truncation -Wno-format-overflow -Wno-address-of-packed-member -O2 -fno-allow-store-data-races -Wframe-larger-than=2048 -fstack-protector-strong -Wno-main -Wno-unused-but-set-variable -Wno-unused-const-variable -fno-stack-clash-protection -g -pg -mrecord-mcount -mfentry -DCC_USING_FENTRY -fno-inline-functions-called-once -falign-functions=16 -Wvla -Wno-pointer-sign -Wcast-function-type -Wno-stringop-truncation -Wno-stringop-overflow -Wno-restrict -Wno-maybe-uninitialized -Wno-array-bounds -Wno-alloc-size-larger-than "-Wimplicit-fallthrough=5" -fno-strict-overflow -fno-stack-check -fconserve-stack -Werror=date-time -Werror=incompatible-pointer-types -Werror=designated-init -Wno-packed-not-aligned -DRT_OS_LINUX -I./include -I/tmp/vbox.0/ -I./include/drm -D__KERNEL__ -DMODULE -DRT_WITHOUT_PRAGMA_ONCE -DRT_ARCH_AMD64 -DRT_OS_LINUX -I./include -I/tmp/vbox.0/ -I./include/drm -D__KERNEL__ -DMODULE -DRT_WITHOUT_PRAGMA_ONCE -DRT_ARCH_AMD64  -DMODULE  -DKBUILD_BASENAME='"vbox_ttm"' -DKBUILD_MODNAME='"vboxvideo"' -D__KBUILD_MODNAME=kmod_vboxvideo -c -o /tmp/vbox.0/vbox_ttm.o /tmp/vbox.0/vbox_ttm.c   ; ./tools/objtool/objtool --hacks=jump_label --hacks=noinstr --hacks=skylake --orc --retpoline --rethunk --sls --static-call --uaccess --prefix=16   --module /tmp/vbox.0/vbox_ttm.o
/tmp/vbox.0/vbox_drv.c:382:10: error: ‘struct drm_driver’ has no member named ‘lastclose’; did you mean ‘postclose’?
  382 |         .master_drop = vbox_master_drop,
      |          ^~~~~~~~~
      |          postclose
/tmp/vbox.0/vbox_drv.c:382:22: error: initialization of ‘const struct drm_ioctl_desc *’ from incompatible pointer type ‘void (*)(struct drm_device *)’ [-Werror=incompatible-pointer-types]
  382 |         .master_drop = vbox_master_drop,
      |                      ^~~~~~~~~~~~~~~~~~~
/tmp/vbox.0/vbox_drv.c:382:22: note: (near initialization for ‘driver.ioctls’)
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:249: /tmp/vbox.0/vbox_drv.o] Error 1
...
```

Thank you.

**Comment by galitsyn-oracle** [comment]
Hi @mabrarov,

Thank you for pointing out. Original fix was targeting RHEL 9.7. I just uploaded new "Development snapshots" test build (r170704+) for Additions which should cover 9.6 as well. Could you please give it a try?

**Comment by mabrarov** [comment]
Hi @galitsyn-oracle,

The new version of Guest Additions (downloaded from https://www.virtualbox.org/download/testcase/VBoxGuestAdditions_7.2.3-170704.iso) which you suggested seems to install without error on Rocky Linux 9.6:

```text
$ cat /etc/*release
NAME="Rocky Linux"
VERSION="9.6 (Blue Onyx)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="9.6"
PLATFORM_ID="platform:el9"
PRETTY_NAME="Rocky Linux 9.6 (Blue Onyx)"
ANSI_COLOR="0;32"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:rocky:rocky:9::baseos"
HOME_URL="https://rockylinux.org/"
VENDOR_NAME="RESF"
VENDOR_URL="https://resf.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
SUPPORT_END="2032-05-31"
ROCKY_SUPPORT_PRODUCT="Rocky-Linux-9"
ROCKY_SUPPORT_PRODUCT_VERSION="9.6"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.6"
Rocky Linux release 9.6 (Blue Onyx)
Rocky Linux release 9.6 (Blue Onyx)
Rocky Linux release 9.6 (Blue Onyx)

$ uname -r
5.14.0-570.39.1.el9_6.x86_64

$ sudo mount -r /dev/cdrom /mnt/cdrom

$ ls -lh /mnt/cdrom/
total 41M
-r--r--r-- 1 root root 1.1K Aug 11 21:04 AUTORUN.INF
-r-xr-xr-x 1 root root 7.0K Sep 29 17:25 autorun.sh
dr-xr-xr-x 2 root root 1.5K Sep 29 17:51 cert
dr-xr-xr-x 2 root root 1.3K Sep 29 17:51 NT3x
dr-xr-xr-x 2 root root 2.8K Sep 29 17:51 OS2
-r-xr-xr-x 1 root root 5.0K Sep 29 17:25 runasroot.sh
-r--r--r-- 1 root root  718 Sep 29 17:51 TRANS.TBL
-r--r--r-- 1 root root 2.2M Sep 29 17:41 VBoxDarwinAdditions.pkg
-r-xr-xr-x 1 root root 4.2K Sep 29 17:41 VBoxDarwinAdditionsUninstall.tool
-r-xr-xr-x 1 root root 2.8M Sep 29 17:30 VBoxLinuxAdditions-arm64.run
-r-xr-xr-x 1 root root 6.4M Sep 29 17:25 VBoxLinuxAdditions.run
-r--r--r-- 1 root root 9.2M Sep 29 17:27 VBoxSolarisAdditions.pkg
-r-xr-xr-x 1 root root 8.4M Sep 29 17:50 VBoxWindowsAdditions-amd64.exe
-r-xr-xr-x 1 root root 4.9M Sep 29 17:49 VBoxWindowsAdditions-arm64.exe
-r-xr-xr-x 1 root root 1.1M Sep 29 17:27 VBoxWindowsAdditions.exe
-r-xr-xr-x 1 root root 6.5M Sep 29 17:49 VBoxWindowsAdditions-x86.exe
-r--r--r-- 1 root root  261 Mar 10  2023 windows11-bypass.reg

$ sudo /mnt/cdrom/VBoxLinuxAdditions.run
Verifying archive integrity...  100%   MD5 checksums are OK. All good.
Uncompressing VirtualBox 7.2.3 Guest Additions for Linux  100%
VirtualBox Guest Additions installer
VirtualBox Guest Additions: Starting.
VirtualBox Guest Additions: Setting up modules
VirtualBox Guest Additions: Building the VirtualBox Guest Additions kernel
modules.  This may take a while.
VirtualBox Guest Additions: To build modules for other installed kernels, run
VirtualBox Guest Additions:   /sbin/rcvboxadd quicksetup <version>
VirtualBox Guest Additions: or
VirtualBox Guest Additions:   /sbin/rcvboxadd quicksetup all
VirtualBox Guest Additions: Building the modules for kernel
5.14.0-570.39.1.el9_6.x86_64.
VirtualBox Guest Additions: reloading kernel modules and services
VirtualBox Guest Additions: kernel modules and services 7.2.3 r170704 reloaded
VirtualBox Guest Additions: NOTE: you may still consider to re-login if some
user session specific services (Shared Clipboard, Drag and Drop, Seamless or
Guest Screen Resize) were not restarted automatically
$ echo $?
0

$ cat /var/log/vboxadd-setup.log
Building the main Guest Additions 7.2.3 module for kernel 5.14.0-570.39.1.el9_6.x86_64.
Building the shared folder support module.
Building the graphics driver module.
```

Thank you!

**Comment by galitsyn-oracle** [comment]
Thank you for the feedback. Closing.
