### ISSUE TITLE
[Bug]: VirtualBox Manager 7.1.12 crashes after each unlock of the screensaver

### ISSUE THREAD

**Issue by erwindon** [VirtualBox/virtualbox#121]
### Version

7.1.12

### Host OS Type

Windows

### Host OS name + version

Microsoft Windows 11 Professional (x64) Build 22631.5624 (23H2)

### Host Architecture

x86

### Guest OS Type

all

### Guest Architecture

x86

### Guest OS name + version

N/A

### Component

Other

### What happened?

When windows screen saver is ended, VirtualBox Manager 7.1.12 always crashes.

### How can we reproduce this?

run VirtualBox Manager.
cause screen saver to be active (e.g. lock screen or wait until screen saver kicks in)
unlock screen saver
VirtualBox Manager crashes immediately.
All VMs keep running without any problem.

based on the error report, I suspect a QT6 issue.

Each crash results in 2 identical crash reports in Windows Log, e.g.:
```
Naam van toepassing met fout: VirtualBox.exe, versie: 7.1.12.19651, tijdstempel: 0x6874f794
Naam van module met fout: Qt6GuiVBox.dll, versie: 6.5.3.0, tijdstempel: 0x6606b642
Uitzonderingscode: 0xc000041d
Foutmarge: 0x00000000000bf450
Id van proces met fout: 0x0xAA4
Starttijd van toepassing met fout: 0x0x1DC070DCE7FC313
Pad naar toepassing met fout: C:\Program Files\Oracle\VirtualBox\VirtualBox.exe
Pad naar module met fout: C:\Program Files\Oracle\VirtualBox\Qt6GuiVBox.dll
Rapport-id: b590ccb2-0076-43cf-831b-ef0054f37159
Volledige pakketnaam met fout: 
Relatieve toepassings-id van pakket met fout: 
```

### Did you upload *all* of your necessary log files, screenshots, etc.?

- [x] Yes, I've uploaded all pertinent files to this issue.

**Comment by AlexanderEichner** [comment]
Not reproducible on a first attempt locally, there must be something related to your Windows configuration triggering this, can you upload a VBoxSVC.log and selectorwindow.log after the crash happened? You can find them under C:\Users\<username>\.VirtualBox

**Comment by Dsen-orcl** [comment]
We also have #170 where process is crashing on Windows host as well while returning from host/display sleep mode. These two can be duplicates, but it's early to tell for sure, I'd keep both opened separately.

**Comment by alxandr3** [comment]
> We also have [#170](https://github.com/VirtualBox/virtualbox/issues/170) where process is crashing on Windows host as well while returning from host/display sleep mode. These two can be duplicates, but it's early to tell for sure, I'd keep both opened separately.

Just to be clear - #170 is the actual VM crashing (VirtualBoxVM.exe) - I never had any issues with VirtualBox Manager (VirtualBox.exe) as described here).

**Comment by erwindon** [comment]
I downgraded to 7.1.8 and the same problem was present.
That is strange since (for me) this problem started just with the upgrade to 7.1.12.
That, together with the observation of @AlexanderEichner, tells me that I should relieve you of this issue.

**Comment by alxandr3** [comment]
Funnily enough, while attempting to reproduce bug 170, I noticed my virtualbox manager disappeared after I unplugged the screen on which is was running and plugged it back in rapidly. I had never noticed this before as it died silently.

Here are the logs that were requested, as well as a crash dump (well 2, with the same timestamp, not sure why it generated two though).

As to reproduce it, I have two screens (DVI cables, as HDMI doesn't always have the following behavior), and when I unplug one, all my open windows switch to the other. Same happens when my screens are waking up from sleep/monitor standby, because one of my screen is slower to come back (has more features like gsync etc) so all windows switch to the 2nd screen and come back to the first, all with 1-2 seconds of waking up so I'm suspecting a race condition in the rendering of the windows somewhere.

[VirtualBox.exe.65012.dmp](https://github.com/user-attachments/files/22123405/VirtualBox.exe.65012.dmp)
[selectorwindow.log](https://github.com/user-attachments/files/22123403/selectorwindow.log)
[VirtualBox.exe(1).65012.dmp](https://github.com/user-attachments/files/22123404/VirtualBox.exe.1.65012.dmp)

**Comment by Dsen-orcl** [comment]
Decided to reopen this issue since there are few users who still able to reproduce it. Investigating it currently.

**Comment by trashcoder** [comment]
I get the same error. Virtualbox (7.2.0.r170228) crashes when i unlock my Linux Host (Manjaro@latest).


Here my last log-entries:

03:10:21.845869 GUI: UIDesktopWidgetWatchdog::sltHandleHostScreenWorkAreaResized: Screen 1 work area is formally resized to: 0x0 x 0x0
03:10:21.871136 GUI: UIMachineLogic: Host-screen count changed
03:10:21.892267 GUI: UIDesktopWidgetWatchdog::sltHandleHostScreenAvailableGeometryCalculated: Screen 0 work area is actually resized to: 0x0 x 1920x1080
03:10:21.892317 GUI: UIMachineLogic: Host-screen available-area changed
03:10:23.114456 GUI: UIMachineLogic: Host-screen count changed
03:10:23.133888 GUI: UIDesktopWidgetWatchdog::sltHandleHostScreenAvailableGeometryCalculated: Screen 0 work area is actually resized to: 0x0 x 1920x1080
03:10:23.133940 GUI: UIMachineLogic: Host-screen available-area changed
03:10:23.158629 GUI: UIDesktopWidgetWatchdog::sltHandleHostScreenAvailableGeometryCalculated: Screen 1 work area is actually resized to: 1920x0 x 1920x1080
03:10:28.240434 ALSA: Using output device "default"

**Comment by galitsyn-oracle** [comment]
Hello,

We just released VirtualBox 7.1.14 and 7.2.4. This issue should be fixed there. Thank you for reporting the issue.

**Comment by Dsen-orcl** [comment]
Issue closed by mistake. There was a fix, but no confirmation so far (as I was not able to reproduce it initially, so blind-fixed it), so keeping it open for now.

**Comment by erwindon** [comment]
After upgrade to 7.2.4 I could not start my VMs any more, uninstall+reinstall fixed that. This is reported elsewhere by others.

(for me) the fix did not solve the original issue:
- (remote->remote) VB Manager crashes each time when I (re)connect to my PC using RDP (using Remote Desktop Manager) when it was still running there. This includes unlocking a screensaver.
- (remote->local) It also crashes when the session is moved back (from RDP) to the actual PC.
- (local->remote) It also crashes when the session is moved back (from actual PC) to RDP.
- (local->local) no problems occur when resuming a session after screensaver on the actual PC.

**Comment by marvin-j97** [comment]
Also find this (or an identical issue) happening on CachyOS (6.18.2-3-cachyos), KDE Plasma 6.5.4, Wayland, VB 7.2.4, VMSVGA

The machine easily works for hours on end, even if the displays turn off, but as soon as they turn on again, the machine simply aborts (no popup) - the debug logs are pretty useless, and just end with:

```
13:08:48.219382 GUI: UIDesktopWidgetWatchdog::sltHandleHostScreenWorkAreaResized: Screen 0 work area is formally resized to: 0x0 x 2560x1440
13:08:48.537182 GUI: UIMachineView::sltPerformGuestResize: Sending guest size-hint to screen 0 as 2512x1377
13:08:48.537197 VMMDev: SetVideoModeHint: Got a video mode hint (2512x1377x32)@(0x0),(1;0) at 0
13:08:48.539160 GUI: UIMediumEnumerator: Medium-enumeration finished!
13:08:48.614611 GUI: UIMachineView::sltPerformGuestResize: Omitting to send size-hint 2512x1377 to guest-screen 0 because this hint was previously sent.
13:08:48.649090 GUI: UIDesktopWidgetWatchdog::sltHandleHostScreenAvailableGeometryCalculated: Screen 0 work area is actually resized to: 0x0 x 2560x1440
13:08:48.652842 GUI: UIMachineLogic: Host-screen count changed
```

**Comment by Dsen-orcl** [comment]
> Also find this (or an identical issue) happening on CachyOS (6.18.2-3-cachyos), KDE Plasma 6.5.4, Wayland, VB 7.2.4, VMSVGA

Right, that's different thing happening on certain Linux hosts. I believe the reason (empty QScreen list) is the same, but crashing place on Linux is unique from what I've gathered across different public defects. Current defect is Windows related. For Linux there is #397 (and I think few other duplicates) .

**Comment by baserkan** [comment]
I will close this isse as it looks like https://github.com/VirtualBox/virtualbox/issues/397 is, hopefully, the same bug. I could not reproduce the issue myself but committed a patch anyways. Hpefully that will resolve the issue. Anyone who wants to give a shot, please check https://www.virtualbox.org/wiki/Testbuilds . Builds of r173931 or later have the patch (7.2 of course). Please let me know if it solve the problem for you or not by commenting on https://github.com/VirtualBox/virtualbox/issues/397 . Thanks a lot
