### ISSUE TITLE
[Bug]: win 11 version-7.2.0 NAT network does not work

### ISSUE THREAD

**Issue by udbxtd2008** [VirtualBox/virtualbox#136]
### Version

7.2.0

### Host OS Type

Windows

### Host OS name + version

Windows 11 24H2 	26100.4946

### Host Architecture

x86

### Guest OS Type

Linux

### Guest Architecture

ARM

### Guest OS name + version

Centos release 7.9.2009

### Component

3D Support

### What happened?

After upgrading VirtualBox from version 7.1.12-169691 to 7.2.0-170228, the NAT network of the virtual machine becomes inaccessible. However, if I downgrade back to version 7.1.12, it works normally again.

### How can we reproduce this?

Host:  win11
Guest: centos 7 

Just upgrade or downgrade the host version from 7.1.12-169691 to 7.2.0-170228 .

Host global network Settings:
NAT network 192.68.139.0/24;  DHCP disable.

At version 7.1.12, guest  can access network: 
[root@localhost ~]# cat /etc/sysconfig/network-scripts/
ifcfg-ens33             ifdown-Team             ifup-post
ifcfg-lo                ifdown-TeamPort         ifup-ppp
ifdown                  ifdown-tunnel           ifup-routes
ifdown-bnep             ifup                    ifup-sit
ifdown-eth              ifup-aliases            ifup-Team
ifdown-ib               ifup-bnep               ifup-TeamPort
ifdown-ippp             ifup-eth                ifup-tunnel
ifdown-ipv6             ifup-ib                 ifup-wireless
ifdown-isdn             ifup-ippp               init.ipv6-global
ifdown-post             ifup-ipv6               network-functions
ifdown-ppp              ifup-isdn               network-functions-ipv6
ifdown-routes           ifup-plip               
ifdown-sit              ifup-plusb              
[root@localhost ~]# cat /etc/sysconfig/network-scripts/ifcfg-ens33 
TYPE=Ethernet
PROXY_METHOD=none
BROWSER_ONLY=no
BOOTPROTO=static
DEFROUTE=yes
IPV4_FAILURE_FATAL=no
IPV6INIT=yes
IPV6_AUTOCONF=yes
IPV6_DEFROUTE=yes
IPV6_FAILURE_FATAL=no
IPV6_ADDR_GEN_MODE=stable-privacy
NAME=ens33
HWADDR=08:00:27:F7:C6:0C
DEVICE=ens33
ONBOOT=YES
IPADDR=192.68.139.4
GATEWAY=192.68.139.1
NETMASK=255.255.255.0
DNS1=8.8.8.8

[root@localhost ~]# cat /etc/redhat-release 
CentOS Linux release 7.9.2009 (Core)
[root@localhost ~]# ifconfig
ens33: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.68.139.4  netmask 255.255.255.0  broadcast 192.68.139.255
        inet6 fe80::a00:27ff:fef7:c60c  prefixlen 64  scopeid 0x20<link>
        ether 08:00:27:f7:c6:0c  txqueuelen 1000  (Ethernet)
        RX packets 243  bytes 28390 (27.7 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 200  bytes 32508 (31.7 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 8  bytes 400 (400.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 8  bytes 400 (400.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

[root@localhost ~]# ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=110 time=34.2 ms
64 bytes from 8.8.8.8: icmp_seq=2 ttl=110 time=34.0 ms

But if upgrade host version to  7.2.0-170228, and keep all of the config unchanged.
At guest network  become inaccessible.

If downgrade to 7.1 again,  network become accessible.

### Did you upload *all* of your necessary log files, screenshots, etc.?

- [x] Yes, I've uploaded all pertinent files to this issue.

**Comment by reedlove** [comment]
I'm also experiencing the same exact thing.
Host: Linux Mint 22.1 (Ubuntu 24.04) amd64
Guest: Windows 11 amd64
Running through the Windows 11 network troubleshooter fixes nothing.

**Comment by InvisibleMass** [comment]
Same problem here with
Host: Ubuntu 24.04
Guest: Ubuntu 24.04

The problem seems to be a failure of the internal DHCP server.

Manually configuring a public DNS server in the guest circumvents the problem.

For a Win10 guest I also had to disable IPv6 to get the connection running (plus a reboot of the Win10 guest).

**Comment by thatnerdjack** [comment]
Hi there! Thanks for taking the time to submit this issue. Could I ask y'all for your VBox.log files? This will hopefully help us narrow down what exactly is going on. Thanks!

**Comment by eugenesan** [comment]
Seems like both NAT and NAT-Network have no DNS exported via DHCP.
Manually setting DNS in the guest fixes the issue.

**Comment by nl6720** [comment]
Here's my [VBox.log](https://github.com/user-attachments/files/21812900/VBox.log).

Host: Arch Linux
- linux 6.16.arch2-1
- virtualbox 7.2.0-1
- virtualbox-host-modules-arch 7.2.0-1

Guest: Arch Linux
- linux 6.16.1.arch1-1
- virtualbox-guest-utils 7.2.0-1

**Comment by FranceBB** [comment]
I can reproduced the bug.

Virtualbox 7.2.0 r170228
Host: Fedora 42 Workstation x64 
Guest: Windows XP Professional x86

[WindowsEmbedded-2025-08-17-01-03-10.log](https://github.com/user-attachments/files/21819485/WindowsEmbedded-2025-08-17-01-03-10.log)

**Comment by reedlove** [comment]
> Same problem here with Host: Ubuntu 24.04 Guest: Ubuntu 24.04
> 
> The problem seems to be a failure of the internal DHCP server.
> 
> Manually configuring a public DNS server in the guest circumvents the problem.
> 
> For a Win10 guest I also had to disable IPv6 to get the connection running (plus a reboot of the Win10 guest).

I can confirm that manually setting the DNS server address, manually, to an external to an external provider works.

**Comment by thatnerdjack** [comment]
Hi all! Just published a test build with a potential fix for a related issue, as well as additional logging that may provide more insight if not already fixed. Please check the "development snapshot" section [here](https://www.virtualbox.org/wiki/Testbuilds) at the bottom of the page and download any snapshot at or later than revision 170264.

As always a reminder: please back up your VMs (or preferably run this on a non-critical machine with non-critical data) as development snapshots are quite literally a snapshot of whatever is in our main branch.

**Comment by FranceBB** [comment]
Thanks for the new builds, but I can only see version 170264 as the latest

[Windows](https://www.virtualbox.org/download/testcase/VirtualBox-7.2.1-170264-Win.exe)	development revision 170264
[macOS/Intel](https://www.virtualbox.org/download/testcase/VirtualBox-7.2.1-170264-OSX.dmg)	development revision 170264
[macOS/ARM64](https://www.virtualbox.org/download/testcase/VirtualBox-7.2.1-170264-macOSArm64.dmg)	development revision 170264
[Linux 64-bit](https://www.virtualbox.org/download/testcase/VirtualBox-7.2.1-170264-Linux_amd64.run)	development revision 170264

Last upload: 2025-08-18T19:39:18Z

**Comment by thatnerdjack** [comment]
Apologies! Should say “170264 or later”. Will update.

**Comment by FranceBB** [comment]
Unfortunately, that didn't work. :(
I can see the following entries in the logs:

00:00:13.206693 NAT: DNS settings changed, triggering update
00:00:13.206710 NAT DNS Update: Stored 1 total nameservers

however in the connection settings I can see that no DNS is specified:
<img width="1123" height="754" alt="Image" src="https://github.com/user-attachments/assets/7bee134c-bea4-4a85-ab7c-a56a45cd3625" />

In the adapter settings both IP and DNS are supposed to be acquired automatically, but the DNS are not really acquired:
<img width="443" height="536" alt="Image" src="https://github.com/user-attachments/assets/c6d8d383-6b35-4d33-bbb4-92627f057ab9" />

[WindowsEmbedded-2025-08-18-21-44-38.zip](https://github.com/user-attachments/files/21844203/WindowsEmbedded-2025-08-18-21-44-38.zip)

**Comment by thatnerdjack** [comment]
We believe now we've isolated the issue. On NAT only, "invalid" (read: incompatible) nameserver addresses weren't being filtered out appropriately. I just sent up a test build that should fix it. Please check the "development snapshot" section [here](https://www.virtualbox.org/wiki/Testbuilds) at the bottom of the page and download any snapshot at or later than revision 1702**7**4 (that is a different number, promise).

As always a reminder: please back up your VMs (or preferably run this on a non-critical machine with non-critical data) as development snapshots are quite literally a snapshot of whatever is in our main branch.

If that still doesn't work, we have a different problem on our hands! If anyone would like to test it, thank you in advance for your feedback!

**Comment by nl6720** [comment]
With "development revision 170274", the issue is gone for me.

**Comment by FranceBB** [comment]
Thanks Jack.
I can confirm that 7.2.1 r170274 solves the issue and the DNS are acquired and populated correctly.
This is Windows 10 Enterprise x64:
<img width="364" height="449" alt="Image" src="https://github.com/user-attachments/assets/9624f710-6d5e-4e97-b245-f3e5ca0da576" />
<img width="360" height="436" alt="Image" src="https://github.com/user-attachments/assets/edaf5742-a7e6-4d18-a147-187da7313dac" />

**Comment by thatnerdjack** [comment]
Thanks all! This issue will be staged for close.

**Comment by quintenvg1** [comment]
I may be a little late to the party, but I have noticed the following.

By default on debian13 (base install with gnome and ssh) > dns is provided by NetworkManager.
When installing the latest version of Virtualbox (https://www.virtualbox.org/download/testcase/VirtualBox-7.2.1-170331-Linux_amd64.run paired with respective expansion pack.)
A nat connection copies the nameservers from /etc/resolv.conf from NetworkManager.

If I change the DNS provisioner from NetworkManager to systemd-resolved, the VM does use 10.0.2.3 as it's DNS server.

Does this have to do with the patches rolled out since the release of v7.2.0?
So we can consider this fixed as long as the host os is using systemd resolved?
This might cause issues when for instance using tailscale and resolvconf.

I agree systemd-resolved is widely used though. But for the sake of investigation let's continue with for instance resolvconf
(or dhcpcd/dhclient... all other systems that do not create a localhost dns server),
 on the host and let's put it behind tailscale (vpn based on split dns and wireguard tunnels. Basically it adds it's own dns server.)
this does work flawlessly since the patch in systemd-resolved.

<img width="1104" height="210" alt="Image" src="https://github.com/user-attachments/assets/7b390dbf-1e17-4da8-a7e4-9f8f322a6930" />

Below is a picture of the resolv.conf file after installing resolvconf and tailscale on the host os.
left host, right guest.

<img width="1145" height="168" alt="Image" src="https://github.com/user-attachments/assets/27dd5e83-9b7d-4c74-a8de-3f316f609dcb" />
Now all works well until I install tailscale inside the guest. Because it's upstream DNS will be 100.100.100.100 instead of 10.0.2.3 or one of the upstream servers tailscale uses if it is unable to resolve a host (such as google.com)

<img width="857" height="665" alt="Image" src="https://github.com/user-attachments/assets/addce344-0eba-4a03-a6d8-4aa1f9e47525" />

Above is a screenshot of "sudo tailscale dns status" on the host.
below is the same result of a VM I installed tailscale on.

<img width="922" height="686" alt="Image" src="https://github.com/user-attachments/assets/5008e637-51e2-4430-8d59-8ad134d3249a" />

As we can see the host has the upstream dns servers of my isp.
If we do the same in the guest. We see that only the hosts that the tailscale dns server can resolve actually are pingable. this makes sense as the machine no longer has any way to resolve hosts outside of what tailscale dns can resolve.
This used to work because before it would have 10.0.2.3 as it's upstream dns server.

I have played with the settings for vbox nat dns proxy and hostresolve

<img width="760" height="235" alt="Image" src="https://github.com/user-attachments/assets/acb6e6ab-0555-4c04-bc5b-2ae1eb44afb5" />

These issues disappear like snow for the sun when using a bridged adapter but there are already so many devices on the network...

Is there any way to have just a button in the virtualbox UI that can toggle between whatever the host provides vs just using 10.0.2.3?
Per VM ideally, but globally is also okay I suppose (don't really know what to call it at this point).

This is my first time ever posting on anything related to Virtualbox so cut me some slack with the documentation.
Logs attached. 

[Logs.zip](https://github.com/user-attachments/files/21993336/Logs.zip)
log 2 and 3 I believe have systemd-resolved on the host. > ping google working
log 1 and 2 have resolvconf and tailscale on the host. > ping google not working (ping google should work if I install systemd resolved now)

Fow nor I will just use systemd-resolved on the host and rely on the patch in the latest dev version.

edit:
about 12 hours after installing systemd-resolved and tailscale on the guest, the dns server on 10.0.2.3 dissapears outright. Not sure what is happening, I am able to ping 10.0.2.3 but not google. It is present in the systemd-resolved log however.

<img width="1893" height="858" alt="Image" src="https://github.com/user-attachments/assets/36d3b3c2-94fc-4dc6-8c7f-4f9d45bca970" />

<img width="1416" height="663" alt="Image" src="https://github.com/user-attachments/assets/ffd80267-9df5-44b0-9df4-cf4c456ed7bc" />


Kind regards.

**Comment by mahnac72** [comment]
Version 7.2.0
Host OS Type
Ubuntu22.04.5LTS

Guest OS Type
Windows7 Ultimate 64bit Enterprise 2015 LTSB  

2 Changes on the NAT settings got the Internet connection up and running on my Guest Windows 7 Ultimate VM run on the Host Linux Ubuntu22.04.5LTS OS

From the Settings / NAT / Enabled Network Adapter 1 / Attached to Bridged Adapter / Name wlp39s0 /  Previous setup not connecting...

Two changes:
1) Promiscuous Mode (Changed) Allow VMs
2) Select Virtual Cable Connected box.

**Comment by galitsyn-oracle** [comment]
Hello,

Thank you for reporting the issue. We just released VirtualBox 7.2.2. This issue should be fixed in this version. Could please give it a try? Packages are available at https://www.virtualbox.org/wiki/Downloads.

**Comment by udbxtd2008** [comment]
> We believe now we've isolated the issue. On NAT only, "invalid" (read: incompatible) nameserver addresses weren't being filtered out appropriately. I just sent up a test build that should fix it. Please check the "development snapshot" section [here](https://www.virtualbox.org/wiki/Testbuilds) at the bottom of the page and download any snapshot at or later than revision 1702**7**4 (that is a different number, promise).
> 
> As always a reminder: please back up your VMs (or preferably run this on a non-critical machine with non-critical data) as development snapshots are quite literally a snapshot of whatever is in our main branch.
> 
> If that still doesn't work, we have a different problem on our hands! If anyone would like to test it, thank you in advance for your feedback!

Sorry for the slow reply,  The issue seems still persist on my machine at version 7.2.2.
Here are logs with verson 7.1.12 and version 7.2.2,
Could you please look into this?@thatnerdjack 

[VBox - v7.1.12.log](https://github.com/user-attachments/files/22994914/VBox.-.v7.1.12.log)
[VBox - v7.2.2.log](https://github.com/user-attachments/files/22994915/VBox.-.v7.2.2.log)

Maybe my host pc problem，recently update to win11 25H2， version 7.2.4 looks fine now.

**Comment by udbxtd2008** [comment]
> Hello,
> 
> Thank you for reporting the issue. We just released VirtualBox 7.2.2. This issue should be fixed in this version. Could please give it a try? Packages are available at https://www.virtualbox.org/wiki/Downloads.

Release 7.2.4 fix， Thanks all❤️

**Comment by mahnac72** [comment]
Yes I found the 7.2.2 version resolved this issue. Thanks
