### ISSUE TITLE
[Bug]: VB7.2.0 GUI font color in drop-down menus matches the background color => unreadable

### ISSUE THREAD

**Issue by metze-samba** [VirtualBox/virtualbox#138]
### Version

7.2.0

### Host OS Type

Linux

### Host OS name + version

Ubuntu 24.04.3 LTS (xubuntu)

### Host Architecture

x86

### Guest OS Type

Linux

### Guest Architecture

x86

### Guest OS name + version

None

### Component

GUI

### What happened?

I updated from 7.1.12 to 7.2.0 and the font in drop-down menus in unreadable as the color matches the background color.

<img width="739" height="487" alt="Image" src="https://github.com/user-attachments/assets/309e98e8-13ef-4583-9160-9485f01f7129" />

<img width="1024" height="695" alt="Image" src="https://github.com/user-attachments/assets/2a5e2e75-224a-40d8-bce4-6d703d8ec9a0" />

### How can we reproduce this?

Install xubuntu 24.04 and virtualbox 7.2.0 and try to use the GUI.

### Did you upload *all* of your necessary log files, screenshots, etc.?

- [x] Yes, I've uploaded all pertinent files to this issue.

**Comment by Ulu-Mulu-no-die** [comment]
I too just upgraded from from 7.1.12 to 7.2.0 and I have exactly the same problem.

Host = Linux MX, version MX-23.6_ahs_x64 (Debian 12 Bookworm), DE = XFCE 4.20

<img width="1071" height="626" alt="Image" src="https://github.com/user-attachments/assets/fc040d48-3cf6-40d8-a9a3-610cbbd98bcd" />

**Comment by Dsen-orcl** [comment]
Could you please check which Qt version is mentioned in VirtualBox About dialog for you? (I mean the original reported as I see another reporter already mentioned that)

**Comment by Ulu-Mulu-no-die** [comment]
I found a solution for myself, no idea if it can work for other people, here it is.

Since XFCE is based on GTK, I installed Qt Config (I didn't need to up to 7.1.12)
`sudo apt install qt5ct`

Then it's necessary to set an environment variable.

For "standard" Debian, the file to create is `~/.config/environment.d/qt5ct.conf` and the content is `QT_QPA_PLATFORMTHEME=qt5ct`.

For Linux MX (my case), the file to create is `~/.config/MX-Linux/qt_plugin.conf` and the content is `qt5ct`.

**Reboot**, launch the app Qt5 Configuration Tool, set a style, click "Apply", and now Virtualbox GUI works (for me at least).

<img width="1107" height="618" alt="Image" src="https://github.com/user-attachments/assets/726e7e55-11a5-4465-98b3-f08ef175ec36" />

**Comment by baserkan** [comment]
Could you please test running VirtualBox with environment variable QT_QPA_PLATFORMTHEME set to xdgdesktopportal. For example by entering the command
export QT_QPA_PLATFORMTHEME=xdgdesktopportal
before running VirtualBox from the same console?

**Comment by metze-samba** [comment]
> Could you please test running VirtualBox with environment variable QT_QPA_PLATFORMTHEME set to xdgdesktopportal. For example by entering the command export QT_QPA_PLATFORMTHEME=xdgdesktopportal before running VirtualBox from the same console?

That works for me, but it would be great if this would if it would not be needed.

The default seems to come from /etc/X11/Xsession.d/56xubuntu-session:
```
# Set default environment vars in Xubuntu
if [ "$DESKTOP_SESSION" = xubuntu ]; then
    # Disable GTK 3.16 overlay scrollbars
    export GTK_OVERLAY_SCROLLING=0
    # QT5 apps to use GTK style
    export QT_QPA_PLATFORMTHEME=gtk2
    # Workaround clutter issue (LP: #1462445)
    export CLUTTER_BACKEND=x11
fi
```

**Comment by baserkan** [comment]
We will try to make it work without explicit setting of the environment variable. I just wanted to see of xdgdesktopportal DBus service is available in your system. gtk2 theme plugin is no longer supported and xdgdesktopportal is one of the ways Qt applications achieve desktop integration.

**Comment by metze-samba** [comment]
> > Could you please test running VirtualBox with environment variable QT_QPA_PLATFORMTHEME set to xdgdesktopportal. For example by entering the command export QT_QPA_PLATFORMTHEME=xdgdesktopportal before running VirtualBox from the same console?
> 
> That works for me, but it would be great if this would if it would not be needed.
> 
> The default seems to come from /etc/X11/Xsession.d/56xubuntu-session:
> 
> ```
> # Set default environment vars in Xubuntu
> if [ "$DESKTOP_SESSION" = xubuntu ]; then
>     # Disable GTK 3.16 overlay scrollbars
>     export GTK_OVERLAY_SCROLLING=0
>     # QT5 apps to use GTK style
>     export QT_QPA_PLATFORMTHEME=gtk2
>     # Workaround clutter issue (LP: #1462445)
>     export CLUTTER_BACKEND=x11
> fi
> ```

It only works for the main VirtualBox Manager application, the menu on the windows of an individual VM
is still broken.

**Comment by baserkan** [comment]
What happens when you start your VM with VirtualBoxVM --startvm vmname ?

**Comment by metze-samba** [comment]
> What happens when you start your VM with VirtualBoxVM --startvm vmname ?

That also works

**Comment by Ulu-Mulu-no-die** [comment]
> Could you please test running VirtualBox with environment variable QT_QPA_PLATFORMTHEME set to xdgdesktopportal. For example by entering the command export QT_QPA_PLATFORMTHEME=xdgdesktopportal before running VirtualBox from the same console?

I changed the variable to "xdgdesktopportal" and it works for me as well!

> gtk2 theme plugin is no longer supported and xdgdesktopportal is one of the ways Qt applications achieve desktop integration

I too have "gtk2" plugin as default in my Xsession.d config file, I guess because MX is still Debian 12.

I checked a fresh install of Debian 13 (in a VM) and the default there is "qt5ct", so I guess as soon as derivatives catch up with the new Debian, the problem will resolve itself without the need of user intervention.

No idea what will happen to LTS distros tho.

**Comment by metze-samba** [comment]
> > > Could you please test running VirtualBox with environment variable QT_QPA_PLATFORMTHEME set to xdgdesktopportal. For example by entering the command export QT_QPA_PLATFORMTHEME=xdgdesktopportal before running VirtualBox from the same console?
> > 
> > 
> > That works for me, but it would be great if this would if it would not be needed.
> > The default seems to come from /etc/X11/Xsession.d/56xubuntu-session:
> > ```
> > # Set default environment vars in Xubuntu
> > if [ "$DESKTOP_SESSION" = xubuntu ]; then
> >     # Disable GTK 3.16 overlay scrollbars
> >     export GTK_OVERLAY_SCROLLING=0
> >     # QT5 apps to use GTK style
> >     export QT_QPA_PLATFORMTHEME=gtk2
> >     # Workaround clutter issue (LP: #1462445)
> >     export CLUTTER_BACKEND=x11
> > fi
> > ```
> 
> It only works for the main VirtualBox Manager application, the menu on the windows of an individual VM is still broken.

After a full reboot it also works for the individual VM windows even if they are launched from the VirtualBox Manager application, so maybe it was only somehow cached before.

**Comment by baserkan** [comment]
I have a, hopefully, working fix for the issue. Please test the next release when it comes out. Please report if it works or not. Thank you.

**Comment by baserkan** [comment]
Should be fixed in 7.2.2. Please test and report if not.

**Comment by galitsyn-oracle** [comment]
Hello,

Thank you for reporting the issue. We just released VirtualBox 7.2.2. This issue should be fixed in this version. Could please give it a try? Packages are available at https://www.virtualbox.org/wiki/Downloads.

**Comment by Ulu-Mulu-no-die** [comment]
I did a fresh install of latest MX23 to avoid "leftovers" of qtconfig, they haven't upgraded to Trixie yet so I used virtualbox 7.2.2 bookworm package and I still have the problem.

<img width="900" height="392" alt="Image" src="https://github.com/user-attachments/assets/fe56d3e0-fd0d-4541-9fb6-312fc74cbd85" />

.  
While the virtualbox trixie package on a fresh Debian 13 install works fine without any user intervention.

<img width="900" height="380" alt="Image" src="https://github.com/user-attachments/assets/289c0155-d058-4ff3-b401-17e132401c6c" />

I'm going to try on a "pure" Debian 12 (no derivatives) and see how it goes.

**Comment by Ulu-Mulu-no-die** [comment]
It's fixed on Debian 12 (fresh install to be sure no user modifications occurred).

<img width="900" height="423" alt="Image" src="https://github.com/user-attachments/assets/d62e9d76-d6e6-4ffe-b017-26fd9fe24d15" />

**Comment by baserkan** [comment]
Thanks for testing. I will take a look at MX23 to see what is missing there.

**Comment by baserkan** [comment]
I see the same problem on MX23. Interestingly the DBUS service (org.freedesktop.portal.Desktop) we check before setting platform plugin theme to xdgdesktopportal is available. This needs some more investigation.

**Comment by baserkan** [comment]
om subsequent tests I cannot  reproduce the problem on MX23. How did you install VirtualBox and do you get any errors/warnings when you try to run it from the terminal?

**Comment by Ulu-Mulu-no-die** [comment]
I installed Virtualbox by downloading the debian 12 package from here: https://www.virtualbox.org/wiki/Linux_Downloads, I launched it from the menu, didn't try the terminal but I will when I finish work and see if it gives any warning.

**Comment by Ulu-Mulu-no-die** [comment]
I did a few tests and something weird happens (MX 23.6, apt full-upgrade before the test).

If I launch virtualbox from the menu, **right after a reboot**, I have the GUI problem I posted above.

If I launch virtualbox from the terminal, I don't have any message of any kind but the menu work correctly.

<img width="747" height="410" alt="Image" src="https://github.com/user-attachments/assets/97208b9c-b6ea-4abb-8f0f-5516cab80b58" />

.

If I close virtualbox and relaunch it from the menu **after doing it from the terminal** the GUI works fine.

If I reboot the machine and launch again from the menu before doing anything else, the GUI "bug" happens.

I tried it 3 times and all 3 times it behaved exactly the same.

I'm sorry I have no idea how to go deeper on this, but at this point it seems to me it has become a MX glitch and not a Virtualbox problem anymore - the bug was consistent on virtualbox 7.2.0, it's not anymore on 7.2.2.

**Comment by baserkan** [comment]
wow. Thanks for the investigation. I have been wondering as to why it happened for me once but not afterward. I will take a look again and try to see if I can dig the cause out. I will add a comment if I find anything.

**Comment by Ulu-Mulu-no-die** [comment]
Thank you! I'd love to know if you find out anything, more out of curiosity than anything else :D

**Comment by baserkan** [comment]
In my case, after a reboot the first run of VirtualBox from the application menu has the problem. When I exit and restart VirtualBox again from the menu the bug disappears. Currently I have no theories as to its cause.
