### ISSUE TITLE
[Bug]: VMs fail to start with critical error on Linux hosts with Kernel 6.12+ due to KVM module conflict

### ISSUE THREAD

**Issue by eugenesan** [VirtualBox/virtualbox#141]
### Version

7.2.0

### Host OS Type

Linux

### Host OS name + version

Ubuntu 24.04.3

### Host Architecture

x86

### Guest OS Type

all

### Guest Architecture

x86

### Guest OS name + version

all

### Component

VMM

### What happened?

Virtualbox should install modprobe config to avoid conflict with KVM kernel module on Linux 6.12+.
Without this config, VMs will fail to start due critical error.

Ex: 
/etc/modprobe.d/virtualbox-kvm-autodisable.conf:
```
#
# In kernel 6.12, KVM initializes virtualization on module loading by
# default. This prevents VirtualBox VMs from starting. In order to
# avoid this, block loading kvm module by default.
# (No need to do manually execute modprobe -r kvm_xxx and so on)
# See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1082157
#
options kvm     enable_virt_at_load=0
```
Note: Borrowed from Debian package.

### How can we reproduce this?

1. Install Virtualbox on Debian 13 or Ubuntu 24.04.3 (or any other Linux host with Kernel 6.12+)
2. Create any VM
3. Try to start

### Did you upload *all* of your necessary log files, screenshots, etc.?

- [x] Yes, I've uploaded all pertinent files to this issue.

**Comment by eugenesan** [comment]
https://github.com/VirtualBox/virtualbox/issues/139 might be related

**Comment by gebailey** [comment]
> [#139](https://github.com/VirtualBox/virtualbox/issues/139) might be related

Looks like it is. If I:

```
rmmod kvm_intel
rmmod kvm
```

Then I'm able to launch the virtual machine as expected. Thanks for the idea!

**Comment by FranceBB** [comment]
just add the following entry in GRUB so that it's used at every boot:

`kvm.enable_virt_at_load=0`

and you won't have any problem.

Example:
```
title Fedora Linux (6.15.9-201.fc42.x86_64) 42 (Workstation Edition)
version 6.15.9-201.fc42.x86_64
linux /vmlinuz-6.15.9-201.fc42.x86_64
initrd /initramfs-6.15.9-201.fc42.x86_64.img $tuned_initrd
options root=/dev/mapper/fedora_localhost--live-root ro resume=/dev/mapper/fedora_localhost--live-swap rd.lvm.lv=fedora_localhost-live/root rd.lvm.lv=fedora_localhost-live/swap quiet kvm.enable_virt_at_load=0 $tuned_params
grub_users $grub_users
grub_arg --unrestricted
grub_class fedora
```

**Comment by galitsyn-oracle** [comment]
Hello,

Thank you for reporting the issue. We just released VirtualBox 7.2.2. This issue should be fixed in this version. Could please give it a try? Packages are available at https://www.virtualbox.org/wiki/Downloads.

**Comment by gitls22** [comment]
Hi,

the issue is still present. I'm on Debian 12 with backport kernel 6.12.43. For VirtualBox 6.2.2r170484,
the entry in grub config

kvm.enable_virt_at_load=0

is necessary  to run a guest os. Otherwise I get the failure message about KVM in use.

Regards

**Comment by galitsyn-oracle** [comment]
> Hi,
> 
> the issue is still present. I'm on Debian 12 with backport kernel 6.12.43. For VirtualBox 6.2.2r170484, the entry in grub config
> 
> kvm.enable_virt_at_load=0
> 
> is necessary to run a guest os. Otherwise I get the failure message about KVM in use.
> 
> Regards

Hi @gitls22,
For pre 6.16 kernels you sill need to follow workaround and either unload `kvm_intel.ko` (or its AMD counterpart) or use `kvm.enable_virt_at_load=0` in kernel command line.
