### ISSUE TITLE
[Bug]: Menus are not visible in dark theme (VirtualBox 7.2)

### ISSUE THREAD

**Issue by maravento** [VirtualBox/virtualbox#150]
### Version

7.2.0 r170228 (Qt6.8.0 on xcb)

### Host OS Type

Linux

### Host OS name + version

Ubuntu Mate 24.04

### Host Architecture

amd64

### Component

GUI

### What happened?

When using VirtualBox 7.2 with a dark system theme, the application menus are not visible, making the interface unusable.

Screenshot:
<img width="888" height="544" alt="Image" src="https://github.com/user-attachments/assets/c3ba36d5-6183-43fe-988e-c882fe51a969" />

### Workaround:

Edit the desktop entry:

`/usr/share/applications/virtualbox.desktop`

Replace the line:

`Exec=VirtualBox %U`

with:

`Exec=env QT_STYLE_OVERRIDE=Fusion virtualbox %U`

Out:

<img width="958" height="544" alt="Image" src="https://github.com/user-attachments/assets/7ad0c1e7-9ace-4fd4-a9a5-e019ed2ff42e" />

**Comment by baserkan** [comment]
Hello,
What is your MATE theme name.
 
```
       _,met$$$$$gg.          serkan@optiplex 
    ,g$$$$$$$$$$$$$$$P.       --------------- 
  ,g$$P"     """Y$$.".        OS: Debian GNU/Linux 12 (bookworm) x86_64 
 ,$$P'              `$$$.     Host: OptiPlex Tower Plus 7010 
',$$P       ,ggs.     `$$b:   Kernel: 6.1.0-34-amd64 
`d$$'     ,$P"'   .    $$$    Uptime: 2 days, 2 hours, 25 mins 
 $$P      d$'     ,    $$P    Packages: 4478 (dpkg), 12 (snap) 
 $$:      $$.   -    ,d$$'    Shell: bash 5.2.15 
 $$;      Y$b._   _,d$P'      Resolution: 1920x1080, 1920x1080 
 Y$$.    `.`"Y$$$$P"'         DE: MATE 1.26.0 
 `$$b      "-.__              WM: Metacity (Marco) 
  `Y$$                        Theme: BlackMATE [GTK2/3] 
   `Y$$.                      Icons: mate [GTK2/3] 
     `$$b.                    Terminal: konsole 
       `Y$$b.                 CPU: 13th Gen Intel i7-13700 (24) @ 5.100GHz 
          `"Y$b._             GPU: Intel Raptor Lake-S GT1 [UHD Graphics 770] 
              `"""            Memory: 5632MiB / 31781MiB 
```

is it maybe possible to share neofetch (or similar) dump. I am not able to reproduce this problem on Debian 12 MATE desktop.

**Comment by baserkan** [comment]
<img width="1282" height="724" alt="Image" src="https://github.com/user-attachments/assets/6f2cefd2-4eb5-4268-9766-0896979c7542" />

**Comment by maravento** [comment]
> neofetch

<img width="815" height="563" alt="Image" src="https://github.com/user-attachments/assets/beeb1eca-8a0a-4e6f-ab58-674d38e636d8" />

**Comment by Dsen-orcl** [comment]
Could you please check which Qt version is mentioned in VirtualBox About dialog for you?

**Comment by maravento** [comment]
> Could you please check which Qt version is mentioned in VirtualBox About dialog for you?

<img width="635" height="503" alt="Image" src="https://github.com/user-attachments/assets/6f8afa66-a7c9-4911-af2f-d3e212556d0d" />

**Comment by maravento** [comment]
It's not the theme. I tried the following desktop themes:
- Dracula
- Ambiant Mate Dark
- Yaru Dark and Yaru (light) 

Same result

<img width="958" height="544" alt="Image" src="https://github.com/user-attachments/assets/6f431f4f-cce9-424c-9ddf-b09eb80a27d3" />

**Comment by Dsen-orcl** [comment]
I wonder if that's somehow related to ditched out (from Qt6) gtk2 style support .. which we are resurrecting for years to be in our Qt6.x, could you please try to test forcing use of GTK2 support? export QT_QPA_PLATFORMTHEME=gtk2

**Comment by maravento** [comment]
> I wonder if that's somehow related to ditched out (from Qt6) gtk2 style support .. which we are resurrecting for years to be in our Qt6.x, could you please try to test forcing use of GTK2 support? export QT_QPA_PLATFORMTHEME=gtk2

It didn't work. Same output.

```
#!/bin/bash
export QT_QPA_PLATFORMTHEME=gtk2
virtualbox
```

**Comment by maravento** [comment]
Solved! (workaround)

`Exec=env QT_STYLE_OVERRIDE=Fusion QT_QPA_PLATFORMTHEME=qt5ct virtualbox %U`

<img width="958" height="544" alt="Image" src="https://github.com/user-attachments/assets/41915bba-23c0-4ac3-a47d-a62f991dfa78" />

Although an "official" solution would be good, that's why I'm not closing the issue.

**Comment by Dsen-orcl** [comment]
Good workaround, thanks for investigation! We'll try to find some official solution.

**Comment by baserkan** [comment]
Could you please test running VirtualBox with environment variable QT_QPA_PLATFORMTHEME set to xdgdesktopportal. For example by entering the command
export QT_QPA_PLATFORMTHEME=xdgdesktopportal
before running VirtualBox from the same console?

**Comment by maravento** [comment]
> export QT_QPA_PLATFORMTHEME=xdgdesktopportal

It's works
```
#!/bin/bash
export QT_QPA_PLATFORMTHEME=xdgdesktopportal
virtualbox
```

PD: Also:

`Exec=env QT_QPA_PLATFORMTHEME=xdgdesktopportal VirtualBox %U`

<img width="958" height="544" alt="Image" src="https://github.com/user-attachments/assets/d0f567ad-2187-4dc5-a3f2-89f72d708501" />

Summary:

The first workaround: Tells Qt to use qt5ct to handle themes

The second workaround: Tells Qt to use the XDG portal for desktop integration, which is more modern and automatic.

Conclusion:

I think it is necessary to explicitly tell VirtualBox 7.2 how it should integrate with the desktop theme system.

**Important:**

These changes only affect the Virtualbox application. They do not apply to virtual machines. When starting a Guest VM, the problem persists.

<img width="660" height="577" alt="Image" src="https://github.com/user-attachments/assets/8f2b95d2-b8b1-46ba-92ef-b066516cba6c" />

**Comment by maravento** [comment]
I'm not a programming expert (I'm a sysadmin). But I think you might be able to analyze this change. I'm not sure if it will work. I'm sure you'll do better than me and improve my proposal.

File:
https://github.com/VirtualBox/virtualbox/blob/main/src/VBox/Frontends/VirtualBox/src/main.cpp

code:
```
/* Configure Qt platform theme integration for better desktop environment compatibility */
        if (!RTEnvGet("QT_QPA_PLATFORMTHEME"))
        {
            const char *pszDesktop = RTEnvGet("XDG_CURRENT_DESKTOP");
            if (pszDesktop)
            {
                char *pszDesktopLower = RTStrDup(pszDesktop);
                if (pszDesktopLower)
                {
                    RTStrToLower(pszDesktopLower);
                    
                    if (   RTStrStr(pszDesktopLower, "mate")
                        || RTStrStr(pszDesktopLower, "gnome")
                        || RTStrStr(pszDesktopLower, "unity")
                        || RTStrStr(pszDesktopLower, "cinnamon"))
                    {
                        RTEnvSet("QT_QPA_PLATFORMTHEME", "xdgdesktopportal");
                        Log(("GUI: Set QT_QPA_PLATFORMTHEME=xdgdesktopportal for desktop: %s\n", pszDesktop));
                    }
                    else if (RTStrStr(pszDesktopLower, "kde") || RTStrStr(pszDesktopLower, "plasma"))
                    {
                        RTEnvSet("QT_QPA_PLATFORMTHEME", "kde");
                        Log(("GUI: Set QT_QPA_PLATFORMTHEME=kde for desktop: %s\n", pszDesktop));
                    }
                    
                    RTStrFree(pszDesktopLower);
                }
            }
        }
```

Changes (Untested):

1. Only works if QT_QPA_PLATFORMTHEME is not already set
2. Automatically detects the desktop environment using XDG_CURRENT_DESKTOP
3. Sets the appropriate theme:
  - xdgdesktopportal for GTK environments (MATE, GNOME, Unity, Cinnamon)
  - kde for KDE/Plasma environments
4. Includes debug logging
5. Properly handles memory with RTStrFree()

**Comment by maravento** [comment]
workarount complete (It works with both the application and the guest VM.):

```
#!/bin/bash

# VirtualBox Qt Theme Fix Launcher
export QT_QPA_PLATFORMTHEME=xdgdesktopportal
export QT_STYLE_OVERRIDE=Fusion
echo "QT_QPA_PLATFORMTHEME=$QT_QPA_PLATFORMTHEME"
echo "QT_STYLE_OVERRIDE=$QT_STYLE_OVERRIDE"
exec VirtualBox "$@"
```

**Comment by baserkan** [comment]
I have a, hopefully, working fix for the issue. Please test the next release when it comes out. Please report if it works or not. Thank you.

**Comment by baserkan** [comment]
Should be fixed in 7.2.2. Please test and report if not.

**Comment by galitsyn-oracle** [comment]
Hello,

Thank you for reporting the issue. We just released VirtualBox 7.2.2. This issue should be fixed in this version. Could please give it a try? Packages are available at https://www.virtualbox.org/wiki/Downloads.

**Comment by maravento** [comment]
> VirtualBox 7.2.2

solved!

**Comment by liar666** [comment]
Using LMDE7 with Vbox 7.2.6 r172322 / Qt 6.8.2 and problem is still there.

I cannot manage to get (even partial) dark mode whatever combination of `qt5ct`/`qt6ct`/`QT_QPA_PLATFORMTHEME`/`QT_STYLE_OVERRIDE`/`QT_ACCESSIBILITY` I use.

`VirtualBox -style Fusion %U` does not work either.

Note: in `qt6ct` (most appropriate since VBox refers to Qt6), the fields "Standard dialogs" only has 2 options: default/Gtk3. I read somewhere that for dark mode to work with Vbox we need Gtk2...
