### ISSUE TITLE
[Bug]: Windows 11 crashes on Fedora 42 with 3D acceleration enabled

### ISSUE THREAD

**Issue by WerySkok** [VirtualBox/virtualbox#238]
### Version

7.2.2

### Host OS Type

Linux

### Host OS name + version

Fedora Linux 42 (KDE Plasma Desktop Edition) x86_64

### Host Architecture

x86

### Guest OS Type

Windows

### Guest Architecture

x86

### Guest OS name + version

Windows 11 Build 26100.6584

### Component

3D Support

### What happened?

Enabling 3D Acceleration causes VM to crash during startup. It works normally without 3D Acceleration.

[VBox.log](https://github.com/user-attachments/files/22453620/VBox.log)

### How can we reproduce this?

1. Install Windows 11 with unattended installation
2. Install Guest Additions in guest machine
3. Shut down machine
4. Enable 3D acceleration
5. Try starting the VM

### Did you upload *all* of your necessary log files, screenshots, etc.?

- [x] Yes, I've uploaded all pertinent files to this issue.

**Comment by Cylindric** [comment]
I'm seeing the same behaviour.

**Comment by AlexanderEichner** [comment]
Thanks for the report, this will hopefully be fixed in the next 7.2.x maintenance release. Would be great if you could try the latest 7.2 testbuild from https://www.virtualbox.org/wiki/Testbuilds .

**Comment by WerySkok** [comment]
Hello, I've tried the latest build (`VirtualBox-7.2-7.2.5_171653_el10-1.x86_64.rpm`) and updated Guest Additions (`VBoxGuestAdditions_7.2.5-171642.iso`), now VM doesn't crash, but it still shows the black screen. Here's the log: [VBox.log](https://github.com/user-attachments/files/23908019/VBox.log).

Also I think I should mention that I have experienced #4 while testing this build.

Since this is a Graphics-related issue, I probably should mention my GPU setup, it's NVIDIA GeForce RTX 3070 Mobile / Max-Q [Discrete] + AMD Radeon Vega Series / Radeon Vega Mobile Series [Integrated].

**Comment by dgrigor7** [comment]
Hello WerySkok
Your 'blank screen' problem could probably caused by dual GPU HW.
The VBox.log hints that VirtualBox uses the discrete GPU GeForce RTX 3070 for rendering.

Could you disable the discrete GPU and recheck if the 'blank screen' problem persists?

> Since this is a Graphics-related issue, I probably should mention my GPU setup, it's NVIDIA GeForce RTX 3070 Mobile / Max-Q [Discrete] + AMD Radeon Vega Series / Radeon Vega Mobile Series [Integrated].

**Comment by WerySkok** [comment]
I've disabled the discrete GPU and the problem still persists.

[VBox.log](https://github.com/user-attachments/files/23959496/VBox.log)

**Comment by galitsyn-oracle** [comment]
Fix should be available with newly released VirtualBox 7.1.16 and 7.2.6.
