### ISSUE TITLE
[Bug]: Windows 11 immediately crashes in VirtualBox if "3D acceleration" is enabled. Workaround in the description.

### ISSUE THREAD

**Issue by d0s1s** [VirtualBox/virtualbox#369]
### Version

7.2.4

### Host OS Type

Linux

### Host OS name + version

Debian 13

### Host Architecture

x86

### Guest OS Type

Windows

### Guest Architecture

x86

### Guest OS name + version

Windows 11 Lastest Build

### Component

3D Support

### What happened?

Windows 11 immediately crashes in VirtualBox if "3D acceleration" is enabled. 

https://forums.virtualbox.org/viewtopic.php?p=557202#p557202

"The workaround that has worked for me was to set the vRAM on the guest to 4096MB. I got the crash on 6144MB and 8192MB but again worked on 16384MB."

I can replicate and confirm this too. 4096MB or 16384MB fix the issue. Please fix 3d support on Windows guest with any VRAM size.

Thanks

### How can we reproduce this?

Set a Windows guest with this vRAM size --> 8192MB or 6144MB.

Star using Windows, and soon the virtual machine crash, for exmple with enter in Full Screen Mode.

4096MB or 16384MB in vRAM fix the issue!

### Did you upload *all* of your necessary log files, screenshots, etc.?

- [x] Yes, I've uploaded all pertinent files to this issue.

**Comment by JBrolin90** [comment]
I can say that my Win11 guest aborts after a verys hort time after boot It varies but I have not noted more than 10 minutes befor crash. My hist is LMDE7 and the Guest is Windows 11 home, 25H2. Virtualbox is 7.2.4 with 14059 MB RAM. Will now try 16384 MB as elaborated on above (I actually had the same in 7.2.2)

**Comment by JBrolin90** [comment]
Just tried 16384 MB and it self aborted, just sitting at the desktop without any applications running

**Comment by Leonito2003** [comment]
I have the same issue, Arch Linux host with Windows 11 Guest, NVIDIA graphics card with nvidia-open drivers, Virtualbox 7.2.4 r170995.
When 3D acceleration is enabled the VM is very unstable and crashes soon after the desktop loads, but changing the allocated RAM to 16384MB seems to make it a lot more stable.

**Comment by AlexanderEichner** [comment]
Please attach at least a VBox.log of the VM crashing (I don't get it why people constantly mark the checkbox but don't supply a VBox.log file). It would also help if could provide us with a core dump so we can see exactly where the crash happens.

**Comment by Leonito2003** [comment]
Here is my VBox.log https://pastebin.com/w9An8NkL 
It doesn't seem to contain anything related to the crash, but the system journal is more interesting as it has the stacktrace https://pastebin.com/M6H8t2qD

**Comment by d0s1s** [comment]
Log is in the forum link of the open issue.

Linux Host + Windows 11 guest with nvidia open propietary driver.

You have the steps to reproduce it and luckly the workaround that fix it.

Thanks

**Comment by Leonito2003** [comment]
I did more testing and the RAM amount is not actually a fix. It delays the crash by some time, but it does not prevent it completely. Only disabling 3D acceleration makes the VM stable for long periods of time.

**Comment by AlexanderEichner** [comment]
Thanks for the report, this will hopefully be fixed in the next 7.2.x maintenance release. Would be great if you could try the latest 7.2 testbuild from https://www.virtualbox.org/wiki/Testbuilds .

**Comment by Leonito2003** [comment]
Thanks for the update !
It does seem a lot more stable, I didn't have any issue on my laptop (Ubuntu, AMD GPU).
However, I still get crashes on my Arch desktop with an NVIDIA GPU. These happen consistently when trying to open MS Edge, the VM is aborted a few seconds after the app appears on screen, before the home tab even loads. Here's the syslog of that happening : https://pastebin.com/VnPBezfQ
Using other graphics-intensive apps seems to be fine, and Firefox also runs without issues.

**Comment by AlexanderEichner** [comment]
Okay, that one is a different crash, as it happens in the DXVK layer. No idea yet what that could be but unfortunately I don't have a system with a NVIDIA GPU.

**Comment by shearercole** [comment]
> Thanks for the report, this will hopefully be fixed in the next 7.2.x maintenance release. Would be great if you could try the latest 7.2 testbuild from https://www.virtualbox.org/wiki/Testbuilds .

Had similar issue, although it's Windows host running Win guest. Had to set guest RAM to 4096MB or 16384MB to avoid crash.
But any RAM size is fine if 3D Acceleration is disabled.

Tested the latest 7.2 builds and no more crash with 3D acceleration.

Host - Windows 10 22H2 | Nvidia driver 591.44 | Virtualbox Version 7.2.5 r171653 with Extension Pack 7.2.x revision 171653
Guest - Windows 11 Pro 25H2 | Guest Additions 7.2.x revision 171642

**Comment by galitsyn-oracle** [comment]
Fix should be available with newly released VirtualBox 7.1.16 and 7.2.6.
