### ISSUE TITLE
[Bug]: 0xc0000005 - The instruction at 0000000000000000 referenced memory at 000001f7607797f8. The memory could not be read.

### ISSUE THREAD

**Issue by mike-friedrich** [VirtualBox/virtualbox#426]
### Version

7.2.4

### Host OS Type

Windows

### Host OS name + version

Windows 11 Enterprise 23H2 build 22631.6060

### Host Architecture

x86

### Guest OS Type

Windows

### Guest Architecture

x86

### Guest OS name + version

WinPE from Windows 10 IoT Enterprise 21H2 

### Component

GUI

### What happened?

[We prepared a custom Windows 10 IoT installer ISO file. This is a normal bootable ISO with a lot extra files.
ISO file size is 41GB.

An empty blank disk guest VM configured for Windows 10 IoT Enterprise 21H2 and set to boot above ISO that contains the standard Windows 10 installation media, just a lot extra files included outside the install.wim that comes with the ISO.

When running the standard Microsoft Setup.exe but starting the VM headless (the ISO must be prepared for unattended run upfront so that no user interaction is required - just boot the ISO), the installation works normally.
When attaching the GUI, the VM crashes immediately. dump file attached
Attached at this stage:
<img width="851" height="745" alt="Image" src="https://github.com/user-attachments/assets/1dbc6446-affc-4c2e-a4f1-c57e9152dc5b" />

The same large ISO boots and installs correctly with VirtualBox 6.1.

[VirtualBoxVM.exe.30560.dmp](https://github.com/user-attachments/files/23891890/VirtualBoxVM.exe.30560.dmp)

[VBox.log](https://github.com/user-attachments/files/23892011/VBox.log)
[VBoxHardening.log](https://github.com/user-attachments/files/23892009/VBoxHardening.log)
[VBoxUI.log](https://github.com/user-attachments/files/23892010/VBoxUI.log)
[W10x64-KnS-Ref.ovf.xml](https://github.com/user-attachments/files/23891926/W10x64-KnS-Ref.ovf.xml)

### How can we reproduce this?

Boot very large ISO files in headless mode and attach the GUI.

### Did you upload *all* of your necessary log files, screenshots, etc.?

- [x] Yes, I've uploaded all pertinent files to this issue.

**Comment by AlexanderEichner** [comment]
Thanks for the report, this will hopefully be fixed in the next 7.2.x maintenance release. Would be great if you could try the latest 7.2 testbuild from https://www.virtualbox.org/wiki/Testbuilds .

**Comment by mike-friedrich** [comment]
> Thanks for the report, this will hopefully be fixed in the next 7.2.x maintenance release. Would be great if you could try the latest 7.2 testbuild from https://www.virtualbox.org/wiki/Testbuilds .

While the error popup disappeared, the VM still crashes and switches into an Aborted state on attach.
Tested with VirtualBox-7.2.5-171653-Win.exe

[VBox.log](https://github.com/user-attachments/files/23916093/VBox.log)
[VBoxHardening.log](https://github.com/user-attachments/files/23916094/VBoxHardening.log)
[VBoxUI.log](https://github.com/user-attachments/files/23916095/VBoxUI.log)

**Comment by mike-friedrich** [comment]
I see "rtR3WinUnhandledXcptFilter caught an exception" in the VBox.log
ExceptionCode=0xc0000005 ExceptionFlags=0x00000000 ExceptionAddress=00007ffe17c8224d

**Comment by mike-friedrich** [comment]
I found a new dump file which i believe is from the test. Unsure if this is relevant or not.

[VBoxHeadless.exe.22824.dmp](https://github.com/user-attachments/files/23916376/VBoxHeadless.exe.22824.dmp)

**Comment by mike-friedrich** [comment]
I did yet another test - after running "bcdedit.exe /set hypervisorlaunchtype off" and rebooting.
And this time i got the popup again:
<img width="518" height="262" alt="Image" src="https://github.com/user-attachments/assets/ec62d243-c77f-4ef9-9ca0-371da2b8636d" />

This time the VM went down into Aborted state only after pressing the OK button.

**Comment by mike-friedrich** [comment]
And this time, no dump was created for VBoxHeadless.exe but instead one for VirtualBoxVM.exe.

[VirtualBoxVM.exe.5912.dmp](https://github.com/user-attachments/files/23916551/VirtualBoxVM.exe.5912.dmp)

[VBox.log](https://github.com/user-attachments/files/23916577/VBox.log)
[VBoxHardening.log](https://github.com/user-attachments/files/23916578/VBoxHardening.log)
[VBoxUI.log](https://github.com/user-attachments/files/23916579/VBoxUI.log)

**Comment by shearercole** [comment]
> Thanks for the report, this will hopefully be fixed in the next 7.2.x maintenance release. Would be great if you could try the latest 7.2 testbuild from https://www.virtualbox.org/wiki/Testbuilds .

Had the same guest VM crash that goes away with 3D Acceleration disabled.
Tested the latest 7.2 builds and no more crash with 3D acceleration.

Host  -  Windows 10 22H2 | Nvidia driver 591.44   |   Virtualbox Version 7.2.5 r171653 with Extension Pack 7.2.x revision 171653
Guest - Windows 11 Pro 25H2  | Guest Additions 7.2.x revision 171642

**Comment by mike-friedrich** [comment]
> > Thanks for the report, this will hopefully be fixed in the next 7.2.x maintenance release. Would be great if you could try the latest 7.2 testbuild from https://www.virtualbox.org/wiki/Testbuilds .
> 
> Had the same guest VM crash that goes away with 3D Acceleration disabled. Tested the latest 7.2 builds and no more crash with 3D acceleration.
> 
> Host - Windows 10 22H2 | Nvidia driver 591.44 | Virtualbox Version 7.2.5 r171653 with Extension Pack 7.2.x revision 171653 Guest - Windows 11 Pro 25H2 | Guest Additions 7.2.x revision 171642

This is a different issue. My configuration has 3d support disabled.

**Comment by galitsyn-oracle** [comment]
Fix should be available with newly released VirtualBox 7.1.16 and 7.2.6.

**Comment by mike-friedrich** [comment]
Unfortunately this is not fixed in VirtualBox version 7.1.16.

<img width="642" height="512" alt="Image" src="https://github.com/user-attachments/assets/56c5afea-7f9e-4bc0-9e70-efce21486d40" />

**Comment by mike-friedrich** [comment]
And it is also not fixed for version 7.2.6a:

<img width="642" height="512" alt="Image" src="https://github.com/user-attachments/assets/a995ed88-1f3d-40e8-845c-244de76ebf16" />

**Comment by mike-friedrich** [comment]
This matches with my previous report that the test version also did not work.
